### ISSUE TITLE
[UPDATE] Add Validation for 10-Digit Phone Number in Registration Page

### ISSUE THREAD

**Issue by AbhilashK26** [AbhilashK26/Codebase#44]
#### Description
The phone number field on the registration page currently does not have validation to ensure the number entered is exactly 10 digits long. This validation is necessary to ensure the accuracy and consistency of the data entered by users.

---

### Task Details
1. **File to Modify:**  
   The phone number validation logic should be added to the registration page, located at `codebase/frontend/src/pages/register.jsx`.

2. **Validation Requirement:**  
   - The phone number must be exactly 10 digits long.
   - If the input is invalid, display an error message:  
     _"Phone number must be exactly 10 digits."_

3. **Testing:**  
   - Verify that the phone number field accepts only 10-digit numbers.
   - Ensure invalid inputs (e.g., fewer or more than 10 digits, or non-numeric characters) show the appropriate error message.

4. **Follow Pull Request Guidelines:**
    - Use a regular expression or other appropriate validation methods to enforce this constraint.
    - Follow the [Pull_request_template.md](Pull_request_template.md) file when submitting the Pull Request.

**Comment by MegaReXR** [comment]
> Hey @AbhilashK26 i am Willing to work on it 
> 

You are assigned for this task.

**Comment by RohitP2005** [comment]
![im2](https://github.com/user-attachments/assets/bee7af01-e95c-45da-b875-5b41ee9d7fba)
![im3](https://github.com/user-attachments/assets/fbcd252c-1e50-44eb-8ace-cb7f446ea8df)
![img1](https://github.com/user-attachments/assets/903271c0-afe3-41ba-877b-15ec891f46ca)
I completed it

**Comment by AbhilashK26** [comment]
Your pull request shows changes of previous issues as well. First pull from main branch, then push your changes to your feature branch. Follow the steps mentioned in CONTRIBUTING.md carefully.

**Comment by MegaReXR** [comment]
Also check successfully registration is possible or not before making pull
request.

**Comment by RohitP2005** [comment]
@okay got it.
@MegaReXR i tried that test case also

**Comment by MegaReXR** [comment]
Then give that screenshot also where skills have multiple entries

**Comment by RohitP2005** [comment]
The alert closes quickly that it is hard to take screenshot

**Comment by MegaReXR** [comment]
You can do like fill the form and take a screenshot and make register then
take another screenshot of the registered user in the home page to verify
any new user added or not.

**Comment by RohitP2005** [comment]
okay got it, thansk @MegaReXR
