### ISSUE TITLE
[ADD] Add a Home Button in the Navbar

### ISSUE THREAD

**Issue by IAMAP842** [AbhilashK26/Codebase#48]
#### Description  
Implement a "Home" button in the Navbar to provide users with quick access to the home page.

---

### Task Details  
1. **File to Modify:**  
   The `Navbar.jsx` file located at `Codebase/frontend/src/components/Navbar.jsx`.

2. **Add Home Button:**  
   - Add a "Home" button to the Navbar.  
   - Ensure the button is styled consistently with other elements in the Navbar.

3. **Redirect on Click:**  
   - When the user clicks the "Home" button, redirect them to the `'/'` route on the frontend.

4. **Follow Pull Request Guidelines:**  
   - Please refer to the [Pull_request_template.md](Pull_request_template.md) file to create your Pull Request for this change.  
   - Ensure proper testing is performed to verify the functionality and styling of the new "Home" button.

**Comment by RohitP2005** [comment]
Hey @IAMAP842 i would like contribute to the issue if its not yet assigned!

**Comment by AbhilashK26** [comment]
> Hey @IAMAP842 i would like to contribute to the issue if its not yet assigned!

Have you registered for the Winter of Open Source event? Please note that this project is part of that event, and we can assign it only to participants who have registered.

**Comment by RohitP2005** [comment]
oh okay then,

**Comment by mottawa** [comment]
I would like to collaborate for this reporitory

**Comment by AbhilashK26** [comment]
> I would like to collaborate for this reporitory

Have you registered for the Winter of Open Source event?

**Comment by AbhilashK26** [comment]
> oh okay then,

You can work on this issue.

**Comment by RohitP2005** [comment]
Thanks .

**Comment by AbhilashK26** [comment]
I have merged the pull request.
